#【默认预设】全局屏蔽process name列表
global_blacklist: []

#【默认预设】重打标参数规则
retag_rules : {
    'chrome.exe':['friendly_name']
}
#RAG日志生命周期模式
rag_keepalive: "auto"

#timeout模式阈值（天）
#rag_timeout: null

#重打标性能空闲阈值
retag_mode: 20 

#重打标CPU异构权重
#cpu_performance_weight: null

#Ollama兼容后端api
LLM_BASE_URL: "http://localhost:11434/v1"

#Ollama key（可选）
#LLM_API_KEY: "ollama"

#LLM模型名称
LLM_MODEL: "gemma-4-e4b"

#Debug模式开关
USER_DEBUG: false
